---
projectTypes:
  - id: project.type.one
    default: true
    region: eastus
    subscriptions:
      - 456bb1ba-04ae-481a-9c55-0e5c1bef0f65
      - 456bb1ba-04ae-481a-9c55-0e5c1bef0f65
      - 456bb1ba-04ae-481a-9c55-0e5c1bef0f65
    subscriptionCapacity: 10
    resourceGroupNamePrefix: TC_ONE_
    providers:
      - id: azure.applicationinsights
        properties:
          dtlvarA: dtlvalueA
          dtlvarB: dtlvalueB
      - id: azure.devops
        properties:
          dtlvarC: dtlvalueC
          dtlvarD: dtlvalueD
      - id: azure.devtestlabs
        properties:
          dtlvarE: dtlvalueE
          dtlvarF: dtlvalueF
  - id: project.type.two
    region: westus
    subscriptions:
      - 456bb1ba-04ae-481a-9c55-0e5c1bef0f65
      - 456bb1ba-04ae-481a-9c55-0e5c1bef0f65
      - 456bb1ba-04ae-481a-9c55-0e5c1bef0f65
    subscriptionCapacity: 5
    resourceGroupNamePrefix: TC_TWO_
    providers:
      - id: azure.applicationinsights
        properties:
          dtlvarA: dtlvalueA
          dtlvarB: dtlvalueB
      - id: azure.devops
        properties:
          dtlvarC: dtlvalueC
          dtlvarD: dtlvalueD
      - id: azure.devtestlabs
        properties:
          dtlvarE: dtlvalueE
          dtlvarF: dtlvalueF
providers:
  - id: azure.applicationinsights
    url: "http://localhost:7101"
    authCode: ""
    events:
      - azure.applicationinsights
    properties:
      dtlvar1: dtlvalue1
      dtlvar2: dtlvalue2
  - id: azure.devops
    url: "http://localhost:7102"
    authCode: ""
    events:
      - azure.devops
    properties:
      dtlvar1: dtlvalue1
      dtlvar2: dtlvalue2
  - id: azure.devtestlabs
    url: "http://localhost:7103"
    authCode: ""
    events:
      - azure.devtestlabs
    properties:
      dtlvar1: dtlvalue1
      dtlvar2: dtlvalue2
users:
  - id: bc8a62dc-c327-4418-a004-77c85c3fb488
    role: Admin
    tags:
      usertag1: tagvalue1
      usertag2: tagvalue2
tags:
  tag1: tagvalue1
  tag2: tagvalue2
  tag3: tagvalue3
properties:
  var1: value1
  var2: value2
  var3: value3
