---
version: 1.0
projects:
  azure:
    region: eastus
    subscriptions:
    - id: b54e1d81-8c0c-4442-9283-9869630d060a
      capacity: 5
    - id: aba7458f-746e-4a59-a3f0-ebf36eddfcf6
      capacity: 5
    - id: 13f34552-b3d0-4099-a672-a8ac7a830db2
      capacity: 5
    defaultSubscriptionCapacity: 10
    resourceGroupNamePrefix: tc_
providers:
- id: azure.applicationinsights
  url: 'http://localhost:7072'
  authCode: ''
  optional: false
  events:
  - azure.applicationinsights
  variables:
    dtlvar1: dtlvalue1
    dtlvar2: dtlvalue2
- id: azure.devops
  url: 'http://localhost:7073'
  authCode: ''
  optional: false
  events:
  - azure.devops
  variables:
    dtlvar1: dtlvalue1
    dtlvar2: dtlvalue2
- id: azure.devtestlab
  url: 'http://localhost:7074'
  authCode: ''
  optional: false
  events:
  - azure.devtestlab
  variables:
    dtlvar1: dtlvalue1
    dtlvar2: dtlvalue2
users:
- id: bc8a62dc-c327-4418-a004-77c85c3fb488
  role: Admin
  tags:
    usertag1: tagvalue1
    usertag2: tagvalue2
- id: aba7458f-746e-4a59-a3f0-ebf36eddfcf6
  role: Creator
tags:
  tag1: tagvalue1
  tag2: tagvalue2
  tag3: tagvalue3
variables:
  var1: value1
  var2: value2
  var3: value3
...