name: TeamCloud - Promote Release

on:
  release:
    types: [ edited ]

env:
  BUILD_CONFIGURATION: Release
  SOURCE_DIRECTORY: ./src
  
jobs:

  build:
    if: '!github.event.release.prerelease'
    name: Promote Pre-release to Release
    runs-on: ubuntu-latest

    steps:
    
    - name: Print stuff
      env:
        STUFF_TO_PRINT: ${{ toJson(github.event.release) }}
      run: echo "$STUFF_TO_PRINT"

    - name: Download asset
      uses: colbylwilliams/download-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_id: ${{ github.event.release.assets[0].id }}
        file_path: ${{ temp }}/NuGet.zip

    - name: Print asset
      run: |
        unzip ${{ temp }}/NuGet.zip
        ls

    # - name: Setup .NET Core
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: '3.1.101'

    # - name: Get Release NuGet Packages
    #   run:  dotnet build ${{ env.SOURCE_DIRECTORY }}/TeamCloud.sln -o Prerelease -c ${{ env.BUILD_CONFIGURATION }} -p:VersionPrefix="${{ steps.gitversion.outputs.majorMinorPatch }}" -p:AssemblyVersion="${{ steps.gitversion.outputs.assemblySemVer }}" -p:FileVersion="${{ steps.gitversion.outputs.assemblySemFileVer }}" -p:IncludeSymbols=true --version-suffix "pre"

    # - name: Publish Pre-release NuGet Packages
    #   run: dotnet nuget push Prerelease/*.nupkg --api-key '${{ secrets.MYGET_TOKEN }}' --source 'https://www.myget.org/F/teamcloud-dev/api/v2/package' --symbol-api-key '${{ secrets.MYGET_TOKEN }}' --symbol-source 'https://www.myget.org/F/teamcloud-dev/symbols/api/v2/package' --skip-duplicate
